### ISSUE TITLE
Latest pyswagger versions differ between PyPy and Github

### ISSUE THREAD

**Issue by workingset** [mission-liao/pyswagger#102]
The latest labeled version on GitHub is v.0.8.23

https://github.com/mission-liao/pyswagger/releases

However, on PyPy the version is  v.0.8.24 and the PyPy download tar points to a file in this github repository:

https://pypi.python.org/pypi/pyswagger

Should v0.8.24 actually be the latest release here?  If so what is the latest commit that we can say is release v.0.8.24?

Regards,
workingset

**Comment by mission-liao** [comment]
@workingset it's my fault, I didn't compose a release on github when releasing that version. It's fixed now, thanks for pointing out.

**Comment by workingset** [comment]
Great news.  Thank you for the quick response.

**Comment by mission-liao** [comment]
close this issue for new, please feel free to reopen it if anything goes wrong.
