### ISSUE TITLE
Question about testing API's with https

### ISSUE THREAD

**Issue by chartjes** [mission-liao/pyswagger#103]
My apologies if this is the wrong place to ask.

I'm trying to test a site with endpoints that are behind https. I saw that you can override url_netloc but I don't see how you tell pyswagger to use https

**Comment by mission-liao** [comment]
@chartjes  I would like to clarify the problem you describe:
 - you are testing a external site
 - the Swagger (OpenAPI) document provided by that site has both scheme defined:
```json
schemes: ["http", "https"]
```
 - you wants to test that site via "https"
In this case, pyswagger would select the first items in that array (which is "http") and doesn't provide a way to pick another one, however, it can be refined to add a way to for users to provide preference.

If it's not what you want, could you describe your problem more precisely?

**Comment by chartjes** [comment]
Thanks for the quick response.

Yes, you are describing what I want to do. So am I correct in thinking if I only put https in the schemes section that will work?

**Comment by mission-liao** [comment]
Yes, that should work. My personal usage is local testing a development server in http, not https. If there is any problem when using https, please feel free to report it.

And I would add a way to provide a preference on schemes, which would be included in next release.

**Comment by mission-liao** [comment]
The Operation object is a 'callable' object in python, the parameter used to call it is exactly the parameter you described in Swagger Document. refer to [here](https://github.com/mission-liao/pyswagger/blob/master/docs/md/tutorial/request.md#provide-parameter) for a mapping from Swagger Parameter to the python primitives.

In your case, it should work when use it in this way:
```python
response = client.request(op(), opt=opt)
```

**Comment by chartjes** [comment]
That did the trick. I'll close this and thank you for your help. FYI us QA folk at Mozilla are starting to use Swagger/OpenAPI as part of the overall testing process and pyswagger is a tool I'm hoping to use a lot.
