### ISSUE TITLE
Exception: Could not find codec for text/html;

### ISSUE THREAD

**Issue by pradeepYogesh** [mission-liao/pyswagger#104]
Hi 
I am using pyswagger to test my local api built using cherrypy. But if I run my test file It s throwing

 File "pyswaggerTest.py", line 13, in <module>
    url_netloc='localhost:8080/' # patch the url of petstore to localhost:8001
  File "/usr/local/lib/python2.7/dist-packages/pyswagger/contrib/client/requests.py", line 69, in request
    raw=six.BytesIO(rs.content).getvalue()
  File "/usr/local/lib/python2.7/dist-packages/pyswagger/io.py", line 391, in apply_with
    data = self.__op._mime_codec.unmarshal(content_type, self.raw, _type=_type, _format=_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/pyswagger/primitives/codec.py", line 34, in unmarshal
    raise Exception('Could not find codec for %s, data: %s, args: %s' % (mime, data, kwargs))
**Exception: Could not find codec for text/html;charset=utf-8, data: Hi, args: {'_format': None, '_type': None, 'name': None}**

I have attached cherrypy and test code with this

> **I am getting request to cherrypy **
[swagger-tester.tar.gz](https://github.com/mission-liao/pyswagger/files/710133/swagger-tester.tar.gz)

Please help me

**Comment by mission-liao** [comment]
You could do this to fix this issue:
```python
from pyswagger import App
from pyswagger.primitives import MimeCodec
from pyswagger.primitives.codec import PlainCodec

mime_codec = MimeCodec()
mime_codec.register('text/html', PlainCodec())
app = App.load("your_swagger.json", mime_codec=mime_codec)
app.prepare(strict=True)
```

It's because for an API service, it's not common to return 'text/html' as content-type. It should usually be 'application/json'. What's your use case to use 'text/html' as content-type for api service?

**Comment by pradeepYogesh** [comment]
Thanks :-). Got it .
Changed my response type in cherrypy .  cherrypy.response.headers['Content-Type'] = "text/json; charset=utf-8" . Closing it
