### ISSUE TITLE
Request connection Timeout feature

### ISSUE THREAD

**Issue by pradeepYogesh** [mission-liao/pyswagger#110]
Hi

Does Pyswagger has a feature to set the connection timeout for the client.request() ???
for example in requests we have 
requests.get(w, verify=False, **timeout**=10)

**Comment by mission-liao** [comment]
You can provide those parameters via 'send_opt' when init client
```
from pyswagger.contrib.clients.requests import Client
client = Client(send_opt=dict(
   timeout=10,
   verify=False,
))
```

**Comment by mission-liao** [comment]
@pradeepYogesh  There is no further action needs to be taken, I'll close this issue and please feel free to reopen it if something goes wrong.
