### ISSUE TITLE
Automatic test case generation given the swagger file for an api

### ISSUE THREAD

**Issue by pradeepYogesh** [mission-liao/pyswagger#111]
I have written swagger file for some api and written some basic test cases for it using the pytest and pyswagger framework.
Can I automate the test case generation based on the swagger file ?

I will attach the swagger file and test-suite if you need to see it

**Comment by mission-liao** [comment]
Hi,

I've written a request template generation with limited randomness. You can check [this document](https://github.com/mission-liao/pyswagger/blob/master/docs/md/tutorial/render.md) to see if this match your requirement.

If not, please describe your requirement more detailedly, and attach the swagger file if it's legal, :)

**Comment by pradeepYogesh** [comment]
I am attaching the swagger file and test suite . I want the test suite to be generated automatically based on the swagger file given.
PFA
[test_suite.tar.gz](https://github.com/mission-liao/pyswagger/files/795922/test_suite.tar.gz)

**Comment by mission-liao** [comment]
I'm a little confused after checking your attachment. You've used **render_all** to generate request template for test, that's what I mentioned in earlier comment.

Did you mean if pyswagger can generate the whole py file containing test suites?

**Comment by pradeepYogesh** [comment]
Yeah. That is  what I meant. I would be a complete automated test case generation by pyswagger.

**Comment by mission-liao** [comment]
Oh, that's an interesting topic, but I think it's not the scope that this project designed to cover.

In your context, the calling sequence of APIs is also random (compared to what we provide in pyswagger now, the calling sequence is fixed, only the input parameters are random). But in most APIs, the calling sequence of API is meaningful so making it random is not that helpful.

======== correct me if I'm misunderstanding your description ===========

Right now you can provide meaningful calling sequences of APIs, pyswagger could generate random input for you and bind parameters (ex, user_id returned by login API) via request template, I think these features could be a least but worked base for automated testing platform.

**Comment by pradeepYogesh** [comment]
Please go through the test cases I have written for the swagger file which I have attached. It covers basic yet power test cases we can think of for any api.
I have just used  pyswagger, pytest and unit test frameworks. It is not difficult.I have written some test fixtures for that.
Basically it covers testing API with different sequence, with different random data types(I have used overriding technique which you had mentioned in your project ie **req._p**)

With this feature in your project. I helps many of the organisations.

Because it generates test cases if you just give the swagger file. :-)

**Comment by mission-liao** [comment]
I've checked & understood your test cases, they are straight forward API to use and thus have no calling sequence problem. However, comparing the work to be done (I can't even know how to implement it, maybe something like [DeepCoder](https://techcrunch.com/2017/02/23/deepcoder-builds-programs-using-code-it-finds-lying-around/)) and the scope this feature can be applied, I think it's not worthy to do it.

This library tends to be small and maintainable, so I would say no to this feature request.

**Comment by pradeepYogesh** [comment]
okay no problem. Thanks for taking your time to go through  my code.
