### ISSUE TITLE
Token in the header to fetch swagger.json

### ISSUE THREAD

**Issue by AlexeKorneev** [mission-liao/pyswagger#115]
Hi,

I would need your help again, struggling with quite simple issue: 
load Swagger resource file into App object:
app = App._create_('http://petstore.swagger.io/v2/swagger.json')

In order to work with swagger.json file, first we need to fetch it, like it's written above, but what if with swagger.json located behind some gateway that require specific 'token' (header) to get that file. How to provide already some specific header (token) to fetch that swagger.json for further testing of endpoints?
What would be the best approach?

Thank you in advance!

**Comment by mission-liao** [comment]
Hi, there was a relative issue before https://github.com/mission-liao/pyswagger/issues/107.

And the corresponding document related to your issue https://github.com/mission-liao/pyswagger/blob/master/docs/md/tutorial/restricted_service.md

This fix is included in v0.8.27. Please feel free to let me know if you have any further questions.

**Comment by AlexeKorneev** [comment]
Thanks again for your help.
Problem is solved in very similar way.
