### ISSUE TITLE
Is there a way to specify an HTTP header to be included in a request?

### ISSUE THREAD

**Issue by MartinDelVecchio** [mission-liao/pyswagger#130]
I can't find any examples of this.

Thanks.

**Comment by mission-liao** [comment]
@MartinDelVecchio 

- Did you mean a header parameter declared in Swagger (Open API) spec, or not ?
- Which header do you want to set ?

I guess you mean headers not declared in spec, then the answer is no, and I can add some way to specify them.

**Comment by MartinDelVecchio** [comment]
Ah, there is my solution.  This is for our API, and I forgot that I could just add an optional header to our Swagger.

So no need for any work on your part; the Swagger standard has what I need.

Thanks!

**Comment by MartinDelVecchio** [comment]
I was able to add a header parameter to my Swagger, and set it via the pyswagger API.

But now I need to do the same thing for another Swagger, which I do not control.

So I would like to renew my request for a way to specify an arbitrary HTTP header to be included in the request.  

I am currently creating an app and a client this way:

        self.app = pyswagger.App._create_ (swagger_location)

        self.auth = pyswagger.Security (self.app)
        self.client = Client (self.auth, send_opt={'verify': False})

And then executing the operation with this call:

        response = self.client.request (self.app.op[operation_id](**kwargs), opt=opt)

I see that the requet() method does not allow me to specify an HTTP header to include.  If there is a different way to use pyswagger that would allow me to add a header, I will gladly use it.

But if there is not, I would appreciate a way to do so.  Perhaps something like this:

 response = self.client.request (self.app.op[operation_id](**kwargs), opt=opt, _headers={"X-My-Header-Name": "Header.Value"})

Thank you.

**Comment by mission-liao** [comment]
@MartinDelVecchio I plan to add an additional parameter `headers` when making request:

```python
# valid headers:
# - {'X-TEST-HEADER': 'aaa'}
# - [('X-TEST-HEADER', 'aaa'), ('X-TEST-HEADER', 'bbb')]  <-- for multiple values for one key
self.client.request (self.app.op[operation_id](**kwargs), opt=opt, headers=headers)
```

The fix is still ongoing, would let you know once finished.

**Comment by MartinDelVecchio** [comment]
Thank you!

**Comment by mission-liao** [comment]
@MartinDelVecchio  the functionality is added in `v0.8.33` and the related document is [here](https://github.com/mission-liao/pyswagger/blob/develop/docs/md/tutorial/customized_headers.md), please let me know if it doesn't work for you.

**Comment by MartinDelVecchio** [comment]
I finally got a chance to test this today, and it works as advertised.

Thanks again for being so responsive!
