### ISSUE TITLE
Exception raised with "format: password" is specified for a string property

### ISSUE THREAD

**Issue by MartinDelVecchio** [mission-liao/pyswagger#134]
My swagger defines an object with a password property:

Password:
  type: string
  format: password

Pyswagger 0.8.33 raises an exception on this:

        if obj.type:
            creater, _2nd = self.get(_type=obj.type, _format=obj.format)
            if not creater:
    >               raise ValueError('Can\'t resolve type from:(' + str(obj.type) + ', ' + str(obj.format) + ')')
    E               ValueError: Can't resolve type from:(string, password)

I recognize this as the same problem I ran into on https://github.com/mission-liao/pyswagger/issues/128.  I have reinstated my workaround that you recommended for that.

But the "Data Types" section of the Swagger spec (https://swagger.io/specification/#dataTypes) mentions this combination:

     password | string | password | A hint to UIs to obscure input.

Can you please add support for this combination?

Thanks.

**Comment by mission-liao** [comment]
@MartinDelVecchio  these issues you reported are addressed in this [PR](https://github.com/mission-liao/pyswagger/pull/136), you can try that branch in your environment and remove those customizations.

Before I release, I would need to add support to a new (from my aspect) primitive: `string:binary`, which may take me a while.

**Comment by mission-liao** [comment]
This issue should be fixed in `v0.8.35`, please feel free to open it if it's not working.

**Comment by MartinDelVecchio** [comment]
Verified.  Thanks!
