### ISSUE TITLE
Installation via pip fails for v0.8.35

### ISSUE THREAD

**Issue by qlixed** [mission-liao/pyswagger#138]
Enviroment:

$ python --version
Python 3.6.2

and

$ pip3 --version
pip 9.0.1 from /<project path removed>/lib/python3.6/site-packages (python 3.6)

Using virtualenv.

$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Fedora 26 (Workstation Edition)"

The installation via pip fails:

$ pip3 install --no-cache-dir -U pyswagger
Collecting pyswagger
  Downloading pyswagger-0.8.35.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 820kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dmktv_i7/pyswagger/setup.py", line 4
        print version
                    ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dmktv_i7/pyswagger/

Previous version works ok:

$ pip3 install -U pyswagger==v0.8.34
Collecting pyswagger==v0.8.34
  Could not find a version that satisfies the requirement pyswagger==v0.8.34 (from versions: 0.0.1, 0.0.2, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10, 0.8.11, 0.8.12, 0.8.13, 0.8.
14, 0.8.15, 0.8.16, 0.8.17, 0.8.18, 0.8.19, 0.8.20, 0.8.21, 0.8.22, 0.8.23, 0.8.24, 0.8.25, 0.8.26, 0.8.27, 0.8.28, 0.8.29, 0.8.30, 0.8.31, 0.8.32, 0.8.33, 0.8.35)
No matching distribution found for pyswagger==v0.8.34

$ pip3 install -U pyswagger==v0.8.33
Collecting pyswagger==v0.8.33
  Downloading pyswagger-0.8.33.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 742kB/s
Requirement already up-to-date: six>=1.7.2 in ./lib/python3.6/site-packages (from pyswagger==v0.8.33)
Collecting pyaml>=15.03.1 (from pyswagger==v0.8.33)
  Downloading pyaml-17.8.0-py2.py3-none-any.whl
Collecting validate_email (from pyswagger==v0.8.33)
  Downloading validate_email-1.3.tar.gz
Collecting PyYAML (from pyaml>=15.03.1->pyswagger==v0.8.33)
Building wheels for collected packages: pyswagger, validate-email
  Running setup.py bdist_wheel for pyswagger ... done
  Stored in directory: /home/qlixed/.cache/pip/wheels/06/63/f1/e4f8912d08618b992eb943b59ead292cbd281f63c52a2c8c1b
  Running setup.py bdist_wheel for validate-email ... done
  Stored in directory: /home/qlixed/.cache/pip/wheels/9b/40/7b/ba10e92e80f0d5541b568eedfff3cc3dedbd3675df538c1dbb
Successfully built pyswagger validate-email
Installing collected packages: PyYAML, pyaml, validate-email, pyswagger
Successfully installed PyYAML-3.12 pyaml-17.8.0 pyswagger-0.8.33 validate-email-1.3

Trying to update to the new version for this neither works:

$ pip3 install --no-cache-dir -U pyswagger
Collecting pyswagger
  Downloading pyswagger-0.8.35.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 820kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dmktv_i7/pyswagger/setup.py", line 4
        print version
                    ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dmktv_i7/pyswagger/

Let me know if you need anything else to move forward this.

**Comment by mission-liao** [comment]
@qlixed this issue should already be fixed in `v0.8.36`, sorry for the inconvenience.
