### ISSUE TITLE
How do I pass a cookie jar to pyswagger?

### ISSUE THREAD

**Issue by MartinDelVecchio** [mission-liao/pyswagger#143]
Before I use pyswagger to test my server, I first have to log into it and get a cookie.  I do this with the requests package:

   `response = requests.post (login_url, auth=(user_name, password), verify=False, timeout=5.0)`
   `self.cookie_jar = response.cookies`

How can I pass this cookie jar to pyswagger, so that it can send the cookie on subsequent requests?

Thanks.

**Comment by mission-liao** [comment]
@MartinDelVecchio 

Inside pyswagger.BaseClient implementation for `requests` library, I use [Session](http://docs.python-requests.org/en/master/user/advanced/#session-objects) to maintain cookies between requests. Therefore, for a login mechanism that save/read auth-info from the same place in cookie, it should work.

If your login mechanism is not the case above, could you describe your use case more precisely (ex. how to get auth-info, and how to use it in subsequent requests) so I could add some way to allow you do it.

**Comment by MartinDelVecchio** [comment]
I have the authentication info, and I am logging in, and I am retrieving the cookie jar:

    self.cookie_jar = response.cookies

I do all of this before I make any calls to pyswagger.  Then when I start my pyswagger stuff, I create a client:

        self.client = Client (None, send_opt={'verify': False})

Then I use that client to execute API calls:

            response = self.client.request (self.app.op[operation_id](**kwargs), opt=opt, headers=headers)

So if the Client constructor allowed me to specify a cookie jar, then you could use that when you create your requests stuff.

Is that what you were getting at?

Thanks again for your always-quick replies.

**Comment by mission-liao** [comment]
@MartinDelVecchio Would you like to try to override the built in client in `pyswagger.contrib.client.requests` ?

```python
from pyswagger.contrib.client.request import Client

class MyClient(Client):
  def __init__(self, auth=None, send_opt=None, cookie=None):
    super(MyClient, self).__init__(auth=auth, send_opt=send_opt)

    # override cookie here
    if cookie:
      self.__s.cookie = cookie # <-- I'm not sure if it's the right way to override requests' cookie

client = MyClient(...) # use this client as usual
```

It's the quickest way I could think that my your trial work. If I need to provide some functionality in pyswagger, I would need to figure a more generic way to support these usage:
- provide an initial cookie: it's your use case
- provide a way to retrieve cookie of response
- provide a way to override cookie of request

It seems not very easy to make everyone happy, if you have any idea about making this part generic and straight forward, please feel free to let me know.

**Comment by MartinDelVecchio** [comment]
I finally got back to trying this, and your suggestion works for all of my needs.

I think this is already a generic solution, and I don't think you have to add anything more.

Thanks!
