### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by kvlahromei** [mission-liao/pyswagger#28]
Hi there, call me wrong, but the example doesn't seem to work anymore?

I tried to fix it (URL, auth, brackets, ...) but unfortunatly got lost in the deeps of some ipython sessions.
Can anybody confirm, if the example is still working (so I'm just working on a broken setup?)

**Comment by mission-liao** [comment]
Ya, I just check that, several things are changed, and found one bug:
- that url would be changed to http://petstore.swagger.io/v2/swagger.json, the client in pyswagger didn't follow redirect.
- the example schema of v2 is different from v1.2, I should refine the example to fit new schema.
  - photoUrls is a required property of Pet model
  - those auth info are not existed.
- a bug is found and not covered by current unit-test, I will create a corresponding test-case and fix it soon
```
  File "ttt.py", line 19, in <module>
    client.request(app.op['addPet'](body=pet_Tom))
  File "/Users/ml/proj/pyswagger/pyswagger/contrib/client/requests.py", line 22, in request
    req, resp = super(Client, self).request(req_and_resp, opt)
  File "/Users/ml/proj/pyswagger/pyswagger/core.py", line 503, in request
    self.__security(req) 
  File "/Users/ml/proj/pyswagger/pyswagger/core.py", line 432, in __call__
    for k, v in six.iteritems(req._security):
  File "/Users/ml/.virtualenvs/pyswagger/lib/python2.7/site-packages/six.py", line 553, in iteritems
    return iter(d.iteritems(**kw))
AttributeError: 'list' object has no attribute 'iteritems'
```

I'm not sure if these cover everything, could you share the error message encountered?

**Comment by mission-liao** [comment]
Just ask a follow-up [question](https://groups.google.com/forum/#!topic/swagger-swaggersocket/GGU9FaS1ldg) to Swagger team. Maybe I'm wrong in somewhere when implementing 2.0 spec.

**Comment by kvlahromei** [comment]
Thanks for your Feedback Liao :-) Indeed this was my problem as I fixed the URL and outdated calls, too. I will try to find my way trough pyswagger, but I guess for other beginners it would be very useful to have an example that works out-of-the-box.

**Comment by mission-liao** [comment]
I plan to update doc recently, would keep you posted in this thread.
Any feedback is welcome.

**Comment by mission-liao** [comment]
just fix the quick start part. The refinement of document is still ongoing. reopen it when quick start doesn't work again (sometimes it's because Swagger team change the sample schema)

**Comment by mission-liao** [comment]
A [tutorial](https://github.com/mission-liao/pyswagger#tutorial) is added to README,
