### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by kvlahromei** [mission-liao/pyswagger#29]
Hi, most people seem to prefer YAML for manually writing swagger specs. Would be nice if you could add support, so a lot more examples etc. can be invoked directly, without converting it manually to JSON etc :-)

**Comment by mission-liao** [comment]
This support is trivial by integrating a yaml parser. The only overhead for me is that an additional dependency would be required.

This request is added to TODO, thanks for asking.

**Comment by mission-liao** [comment]
I just finished the support of YAML, this issue is closed, reopen it once you found something wrong.
