### ISSUE TITLE
python library for creating swagger 2.0 rest api

### ISSUE THREAD

**Issue by prashanthmadi** [mission-liao/pyswagger#35]
Hi, I was trying to create a swagger 2.0 python rest api and consume the same towards client side using pyswagger. I tried django-rest-swagger but it has generated a swagger 1.2 doc. Could you help me with  any python library which would help me create swagger 2.0 python rest api app towards server side.

**Comment by mission-liao** [comment]
Hi,

   There is an [issue](https://github.com/marcgibbons/django-rest-swagger/issues/250) opened in that project one month ago, I guess the maintainer didn't plan to implement that part, and it's a big change from 1.2 to 2.0.

   IMO, I have these options:
   - Adapte a converter: https://www.npmjs.com/package/swagger-converter
   - By hands: https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide
   - That last one is implement a forward converter with code inside pyswagger, it's not hard but still takes me days to implement. I open an [issue](https://github.com/mission-liao/pyswagger/issues/36) for record

**Comment by prashanthmadi** [comment]
Thanks for info :+1:

**Comment by mission-liao** [comment]
I just made pyswagger able to dump Swagger object, which means you can load your Swagger 1.2 document, and dump it into a Swagger 2.0 document.

```python
from pyswagger import SwaggerApp
import json

app = SwaggerApp.create('/directory/contains/your/resource/files/')
with open('./swagger.json', 'w') as r:
   r.write(json.dumps(app.dump(), indent=2))
```

These changes are in master branch now, and will go into v0.8.10.
