### ISSUE TITLE
ValueError from example (due to type: object?)

### ISSUE THREAD

**Issue by bonzotronix** [mission-liao/pyswagger#38]
Using the latest pyswagger from github, I get the following error when I run the example from the tutorial:

```
Traceback (most recent call last):
  File "./example.py", line 20, in <module>
    client.request(app.op['addPet'](body=pet_Tom))
  File "/usr/local/lib/python2.7/dist-packages/pyswagger/spec/v2_0/objects.py", line 280, in __call__
    _convert_parameter(deref(p))
  File "/usr/local/lib/python2.7/dist-packages/pyswagger/spec/v2_0/objects.py", line 264, in _convert_parameter
    c = p._prim_(v)
  File "/usr/local/lib/python2.7/dist-packages/pyswagger/spec/v2_0/objects.py", line 186, in _prim_
    return prim_factory(self.schema, v) if i == 'body' else prim_factory(self, v)
  File "/usr/local/lib/python2.7/dist-packages/pyswagger/primitives.py", line 433, in prim_factory
    raise ValueError('Can\'t resolve type from:(' + str(obj.type) + ', ' + str(obj.format) + ')')
ValueError: Can't resolve type from:(object, None)
```

If I modify the swagger json spec file and remove the line
```
  "type": "object",
```
from the Pet, Tag and Category definitions, then things seem to work correctly.

**Comment by mission-liao** [comment]
Thanks for reporting issues. There is a [TODO](https://github.com/mission-liao/pyswagger/commit/ea6ca24ae4a8ab38943be47be9a4349d36cb92a4#diff-cb94ff845998ec620acf59099d2f316aR9) for this.

In Swagger spec, there is nothing related to "object" in [DataType](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types) section, but in examples.

I will(and should) support this in next week, which will be related to another TODO item: "Pluggable primitive system, allowing to use new 'type' & 'format' in Swagger." (An idea borrowed from [flex](https://github.com/pipermerriam/flex))

**Comment by bonzotronix** [comment]
Thanks for the quick response.

It looks like the "object" type is used in the [JSON Schema Object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object), not in the Swagger primitives.  Each field of the Swagger [Definitions Object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#definitions-object) has a JSON Schema Object as its value.

**Comment by mission-liao** [comment]
Should be fixed in v0.8.11

**Comment by bonzotronix** [comment]
Seems to be working now.  Thanks for the quick resolution!

**Comment by mission-liao** [comment]
Thanks for reporting issues, :)
