### ISSUE TITLE
SchemaError when json without operation_id

### ISSUE THREAD

**Issue by n-elloco** [mission-liao/pyswagger#42]
My json file has 2 paths without operationId and identical tags:

    "paths": {
        "/api/1/game/login": {
            "post": {
                "summary": "Login to game",
                "tags": [
                    "game"
                ],
                "description": "Some description here",
                "parameters": [],
                "responses": {}
            }
        },
        "/api/1/game/start": {
            "post": {
                "summary": "Start the game",
                "tags": [
                    "game"
                ],
                "description": "Some description here",
                "parameters": [],
                "responses": {}
                }
            }
        }
    }

I try create app

`SwaggerApp.create(args.path)`

Error in output:

    Traceback (most recent call last):
      File ".../pyswagger/core.py", line 359, in create
	app.prepare(strict=strict)
      File ".../pyswagger/core.py", line 330, in prepare
	s.scan(root=self.__root, route=[tr, cy])
      File ".../pyswagger/scan.py", line 125, in scan
	handle_cls(cls)
      File ".../pyswagger/scan.py", line 118, in handle_cls
	ret = ff(the_self, path, obj, self.app)
      File ".../pyswagger/scanner/type_reducer.py", line 26, in _op
	raise SchemaError('duplicated key found: ' + new_scope)
    pyswagger.errs.SchemaError: duplicated key found: game

The problem in method `_op`. I suggest to make a name if specification hasn't `operationId` from the  path and the method of operation. For example `post_api_1_game_login` or a similar. I could make a pull request if needed

**Comment by mission-liao** [comment]
Your json seems valid, so that maybe a bug when operationId is "" or None, and this case seems not be included in tests. I will take a look later (now it's mid-night in my time zone), and fix it when confirmed.

Thanks for reporting issues, that helps a lot.

**Comment by mission-liao** [comment]
pyswagger still try to push an **Operation** with empty operationId and non-empty tags into **ScopeDict**. However, it's really meaningless to do that. Once stoping that behaviour, this issue is fixed.

New build and [test](https://github.com/mission-liao/pyswagger/tree/master/pyswagger/tests/data/v2_0/schema/emptyOp) is provided for this issue. Thanks for reporting. Let me know if anything missed.

**Comment by n-elloco** [comment]
Thanks for fix, but now property `op` on SwaggerApp class does not collect all operations from json. As if there is no operations. Therefore, I suggested if there is no `operationId`, then we make name from method and path.

Fix for example:

    class TypeReduce(object):
        ...
        def _op(self, path, obj, _):
            ...
            if not name:
                name = '{}_{}'.format(obj.method, obj.path[1:].replace('/', '_'))

**Comment by mission-liao** [comment]
Thanks for providing a possible workaround.
However, there could be still duplicated keys in your fix.
For example:
/a/b/c -> a_b_c
/a_b_c -> a_b_c

It's hard to make everyone happy. The only safe way to access Operation(s) is:
 - via JSON pointer
 - providing operationId

I think a better way for you is to build a customised reducer to collect those Operation(s), with your own key format. Below is an runnable script to demonstrate how to do it

```python
from pyswagger import SwaggerApp, scan
from pyswagger.spec.v2_0.objects import Operation

class MyReducer(object):
    class Disp(scan.Dispatcher): pass

    def __init__(self):
        self.op = {}

    @Disp.register([Operation])
    def _op(self, path, obj, _):
        obj.operationId # operationId
        obj.tags # tags
        self.op[path] = obj # path to obj (json point)

app = SwaggerApp.create("./pyswagger/tests/data/v2_0/wordnik") # path to your document

reducer = MyReducer()
scanner = scan.Scanner(app)
scanner.scan(route=[reducer], root=app.root)
print reducer.op
```

P.S. one drawback of this approach is that: SwaggerApp.root would always be the latest version of Swagger, which means its properties might be changed when Swagger has new version.

**Comment by n-elloco** [comment]
Thanks, I will try your suggestion.
