### ISSUE TITLE
Generate request template for operation

### ISSUE THREAD

**Issue by WangJiannan** [mission-liao/pyswagger#44]
In http://petstore.swagger.io/#!/pet/addPet, click the right yellow block, a request template is generated and auto-filled in the parameter value area.

This feature is cool and it's very convenient for users. Could anyone help to support it in pyswagger?

My proposal is add a function in `class Operation`:
```python
def generate_request_template(self, minimal, primitive_type_generator):
    """
    minimal: boolean, only generate 'required' fields if True
    primitive_type_generator: function to generate value for primitive type,
                              function parameter list: type, format, name
    """
```

**Comment by mission-liao** [comment]
Hi, pyswagger is a small project, and currently, I'm the 'anyone' here.

I think it's possible to add this feature in pyswagger (further investigation maybe required), but before implement it, I would like to clarify its use case.

**Comment by WangJiannan** [comment]
You just tell my use case!

To be honest, I'm writing a data-driven testing framework for RESTful API testing based on Swagger. It's done (on top of pyswagger) but I still want to offer an auxiliary tool for test case creation. Request template generation would be helpful and I think it's a feature that pyswagger is nice to have.

Actually, I did some work on API help generation (just like Data Type Model description in swagger-ui). It's not hard to generate request template in the same way. However, I would like to make sure thing is done in the right way (my code is kind of hack and it only works in spec 2.0), so I come here to ask thorough solution.

By the way, here is what the tool looks like (I'll push my work to github soon):
```python
>>> petstore = load_swagger('http://petstore.swagger.io/v2/swagger.json')
>>> petstore.addPet
some help (parameters, etc.)
>>> request = petstore.addPet.request_template(...)
>>> #modify request
>>> response = petstore.addPet(request)
>>> make_test_case(request, response)
...
```

**Comment by mission-liao** [comment]
Ok, got it, that would be a useful feature for black-box testing.

Two functions would be added:
- accept a [Schema Object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaObject) to generate a random primitive corresponding to that object.
- accept an array of [Parameter Object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameterObject) to generate a whole set of primitives for an operation.

options:
- minimal: only generate 'required', as you said.
- max_recursion: how many level of recursive allowed for a Schema object.

output:
- primitives acceptable by pyswagger.

Things above might be changed after I dig into those code. Stay tuned.

**Comment by WangJiannan** [comment]
That's great, thanks!

**Comment by mission-liao** [comment]
@WangJiannan  I just merge 'renderer' into master

Before releasing this feature, I would like to hear your feedback first. Here is a [tutorial](https://github.com/mission-liao/pyswagger/blob/master/docs/md/tutorial/render.md) for basic usage.
Please feel free to throw anything, I will try to catch it.

**Comment by WangJiannan** [comment]
@mission-liao Awesome, I just integrate it with my tool and it works perfect. Thanks for your work!

**Comment by mission-liao** [comment]
ok, I will release/review a version tomorrow, thanks for your feedback.

**Comment by WangJiannan** [comment]
During some testing, I find the generated template is empty several times, which is due to optional parameter/property is generated by 50% possibility. I think it would be better to add another options maximal_property/maximal_parameter.

**Comment by mission-liao** [comment]
@WangJiannan Does 'maximal_property/maximal_parameter' means generating every possible property / parameter? If so, it seems nice to add this option and I will finish it later today.

**Comment by WangJiannan** [comment]
Exactly, thanks.

**Comment by WangJiannan** [comment]
Here is a bug: set max_str_length to small value, let's say 5. Random generated string from enum array maybe larger than 5, which causes ValueError in io.py:72.

**Comment by mission-liao** [comment]
Hi, I think the codebase we talked are different, in 'master', io.py:72 is a comment.

'enum' takes priority over 'max_str_length', and 'max_str_length' has nothing to do with code in io.py. (almost everything related to Renderer is separated from original code.)

Could you provide more detail about the bug?

**Comment by WangJiannan** [comment]
My bad, the exception is raised at [primitives/render.py:72](https://github.com/mission-liao/pyswagger/blob/master/pyswagger/primitives/render.py#L72).
The root cause is: after randomly choose one value from enum array at [render.py:229](https://github.com/mission-liao/pyswagger/blob/master/pyswagger/primitives/render.py#L229), it will next check the chosen string length with 'max_str_length' at [render.py:67](https://github.com/mission-liao/pyswagger/blob/master/pyswagger/primitives/render.py#L67), which doesn't make sense for enum string.

**Comment by mission-liao** [comment]
Got it, maybe a reasonable behavior is to trust what we got from enum.
Same issue would be happened for int, float.

But what about 'email'? if email from enum is invalid, shouldn't we raise an exception?
Any comment?

**Comment by WangJiannan** [comment]
Agree, just trust what we got is acceptable, including email.
I wouldn't recommend raise exception for invalid email from enum array during render, instead, we can do validation at swagger file loading phase and post warning/error there if anything is invalid.

**Comment by mission-liao** [comment]
It seems this issue is fixed long ago. To be clear, values come from "enum" would be accepted by default, but they still need to match the basic format if pyswagger pass those "enum" to corresponding constructor, ex.
 - date
 - datetime
 - uuid
