### ISSUE TITLE
Add a gitter chat room

### ISSUE THREAD

**Issue by timtan** [mission-liao/pyswagger#45]
it is popular recently.  user/developer can discuss thing together. 

if @mission-liao think it is good.  I can help add the room

**Comment by mission-liao** [comment]
Thanks for feedback.

I will check the issue list on github in daily basis. But I can't promise that I will monitor the chat room (a chat root usually means an expectation of faster response time). Therefore, I think github-issue is enough for this project.

**Comment by timtan** [comment]
thanks for your kindly feedback
