### ISSUE TITLE
add requests in setup.py

### ISSUE THREAD

**Issue by timtan** [mission-liao/pyswagger#46]
After reading document.  I know request is abstracted. however, the simple example in README.md will fail because the lack of request package.   how about add requests in your setup.py so the basic sample in README.MD can execute without error.

**Comment by mission-liao** [comment]
Sorry for spending time to figure this out.

I would like to make this library neutral to network-io library, for developers testing their own flask server, 'requests' is useless to them.

I will update the 'installation' section of readme for each deps of different usage, and add some warning banner on tutorial/samples. What do you think of this refinement?

**Comment by timtan** [comment]
I think it is good. people can know your intension better.
