### ISSUE TITLE
When no host specified by spec, entire spec url is used as host

### ISSUE THREAD

**Issue by ameade** [mission-liao/pyswagger#58]
If I do not specify a 'host' in my swagger spec, pyswagger attempts to use the entire spec URL I gave it for the host. Swagger spec states "If the host is not included, the host serving the documentation is to be used (including the port)."

Example, if I do:
URL = hostname/api/spec
app = pyswagger.SwaggerApp._create_(URL)

It then attempts to use URL as the host for all requests.
request.url: hostname/api/spec/api/auth

when it should be 'hostname/api/auth'

Thanks! This should be a simple one.

**Comment by mission-liao** [comment]
Ya, it's definitely a bug, thanks for reporting, I will fix it later today.

**Comment by mission-liao** [comment]
should be fixed in 0.8.17, reopen it if you find anything broken. :)

**Comment by ameade** [comment]
It works, thanks!
