### ISSUE TITLE
when use client.request to send a request to https url it falied with SSL3_GET_SERVER_CERTIFICATE

### ISSUE THREAD

**Issue by LouisZou** [mission-liao/pyswagger#60]
the error message like the following:
requests.exceptions.SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

when I new the client and send the request , can I  add a parameters like "verify=False"?
I can use this parameters in requests.get()

**Comment by LouisZou** [comment]
in the source code : 
pyswagger/contrib/client/requests.py :46
if I add a parameters "verify=False", it work well.

so  how can I transfer this parameter into the client.request(op(body={}))

**Comment by mission-liao** [comment]
Hi, good work & finding. Those client implementation are made for common cases. One possible remedy for your case is to add an additional parameter when constructing the client object:
```python
from pyswagger.contrib.client.requests import Client
client = Client(auth, verfiy=False) # the new way
```

All requests sent through this client would skip verification of ssl certificate, what do you think?

**Comment by LouisZou** [comment]
Thanks mission-liao.
That's a good idea to add the SSL cert flag to Client object. so we can provide the different requests that whether use the verification when call the operation of restful API.

**Comment by mission-liao** [comment]
OK, I would provide a fix on it next Monday, should be an easy fix.

**Comment by mission-liao** [comment]
The fix would be included in next release, but right now, I'm still waiting for another PR for 'extensible content-type'.

**Comment by mission-liao** [comment]
This options required by requests.Session.send could be passed when constructing pyswagger.contrib.client.requests.Client
```python
from pyswagger.contrib.client.requests import Client

client = Client(send_opt=dict(verify=False))
```
