### ISSUE TITLE
The url is somethins strange for my request

### ISSUE THREAD

**Issue by LouisZou** [mission-liao/pyswagger#62]
I run my request and found the log like the following:
pyswagger.core - INFO - request.url: //myserver//user/

I think it should be:
http://myserver/user/

1, there is no scheme in the begin of the url
2, there are double '//" between the server and the path.

Is this correct?

**Comment by LouisZou** [comment]
Sorry for this issue.
the item2, I think I can set the basepath to "" instead of "/" to avoid it.

**Comment by mission-liao** [comment]
For item#1, the scheme used to generate an request is based on 'schemes' field in [Swagger Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object), or in [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object). If you didn't provide that field, then the scheme of the url used to fetch your API spec would be used instead.

**Comment by LouisZou** [comment]
Thanks mission-liao.
I think it only does not display in the url. the request can be executed with correct shecmes (https/http)

**Comment by mission-liao** [comment]
Ah, I found the scheme part should be displayed in another line of log:
```python
logger.info('request.url: {0}'.format(req.url))
logger.info('request.header: {0}'.format(req.header))
logger.info('request.query: {0}'.format(req.query))
logger.info('request.file: {0}'.format(req.files))
logger.info('request.schemes: {0}'.format(req.schemes))  # <-- here
```
Glad that things work

**Comment by LouisZou** [comment]
Thanks mission-liao .
I noticed the debug info, that's very useful for debugging .

**Comment by mission-liao** [comment]
It should be fine to close this issue, please feel free to reopen it when things go wrong.
