### ISSUE TITLE
Ignores 'additionalProperties' on object types

### ISSUE THREAD

**Issue by ameade** [mission-liao/pyswagger#64]
The following spec should work but pyswagger seems to ignore additionalProperties on an object type. I did not see any tests for this case. See section 'Model with Map/Dictionary Properties' at  http://swagger.io/specification/#schemaObject

type: object
additionalProperties:
  type: string

**Comment by mission-liao** [comment]
Hi, thanks for reviewing pyswagger. Actually, pyswagger 'should' take care of 'additionalProperties' already (we have test case for it, search 'AdditionalPropertiesTestCase').

If it doesn't work in your swagger document, just let me know :)

**Comment by ameade** [comment]
Below is my spec. 

I am trying to do
req, res = app.op[operation](body={'username': "myusername",
                                                        'units': {'test': 0})
But the 'test' attribute isn't being set in the request. 

"definitions": {
    "MyRequest": {
      "properties": {
        "units": {
          "additionalProperties": {
            "format": "int32", 
            "type": "integer"
          }
        }, 
        "username": {
          "type": "string"
        }
      }
    }, 
post": {
        "description": "", 
        "parameters": [
          {
            "in": "body", 
            "name": "body", 
            "schema": {
              "$ref": "#/definitions/MyRequest"
            }
          }
        ], 
        "responses": {
          "202": {
            "description": ""
          }
        }, 
      }
    }, 
}

**Comment by mission-liao** [comment]
@ameade I tried this sample code / definition and it works
```python
from pyswagger import SwaggerApp

# init SwaggerApp with customized primitive factory
app = SwaggerApp.create('./swagger.json')
op = app.s('/t').get
req, resp = op(body=dict(
    utils=dict(
        a=1,
        b=2
    ),
    username="Tom"
))

print req._p['body'] # expected: {u'body': {'username': 'Tom', 'utils': {'a': 1, 'b': 2}}}
```
```json
{
   "swagger":"2.0",
   "host":"http://test.com",
   "basePath":"/v1",
   "paths":{
      "/t":{
         "get":{
            "parameters":[
               {
                  "in":"body",
                  "name":"body",
                  "schema":{
                     "$ref":"#/definitions/MyRequest"
                  }
               }
            ],
            "responses":{
               "default":{
                  "description":"void"
               }
            }
         }
      }
   },
   "definitions":{
      "MyRequest":{
         "properties":{
            "units":{
               "additionalProperties":{
                  "format":"int32",
                  "type":"integer"
               }
            },
            "username":{
               "type":"string"
            }
         }
      }
   }
}
```

Could you help to provide reproducible sample code / swagger spec if it doesn't solve your case?

**Comment by mission-liao** [comment]
No more update on this case, reopen it when acquiring more info.
