### ISSUE TITLE
How to get the name of the parameter for "path" in request "GET" just like "/user/{username}"

### ISSUE THREAD

**Issue by LouisZou** [mission-liao/pyswagger#67]
I have a definition file and there is a path like this:
"/user/{**_username_**}"

when I will get this op and run it I can write the code like the following sample:
response = client.request(myop(**_username_**="Tom"))

But when I want to traverse each op and test it, how can I know the parameter "{username}", is there any native method to get it. my meaning is I have only a swaggerAPP object and no the original json file. so I don't know whether the parameter is "username" or "user" or other value.

**Comment by mission-liao** [comment]
Can you describe the use case more detailed? I don't understand why you would need to access something you provide.

It's possible to get this parameter back, however, it's not an official supported API of pyswagger.
```python
resp, req = myop(username="Tom")
assert req._p['path']['username'] == "Tom"
```

**Comment by LouisZou** [comment]
Thanks mission-liao,
in my case , the details like the following:
1. in definition:
  "paths": {
        "/user/{username}" :{
              "get": {
                   "operaionId":"getUserByName"
          ...
2. I will call it as the following:
  myop.app.op["getUserByName"]
  myop(user="Tom")  ## user is the variable in path included by "{" and "}"

3. myquestion is as I descrinbed in Issue 66#, I will itarate each of the apis and test it.
   Now I have test data "Tom", And I want to know the name of parameter, it is "user".
   I want to a interface from pyswagger just like:
  app.op.Idlist()  -- this is a sample
  op.getPathName()  -- this is a sample
  so that I can write code like the following:
  for id in app.op.Idlist():
     myop = app.op[id]  --> I can get each of the API
    path_name_for_get = myop.getPathName() -- it will return "user" maybe return a list for multiple variuables?
   client.request(myop( path_name_for_get = "Tom") -- this sentence should be fixed because the argument should not be a variable.
and I will use eval to fix this sentence.

Is there any method to realize the above 2 interface?

**Comment by LouisZou** [comment]
For my case ,that's meaning assume I don't know the word "username" in the path. so I want to get it from the object App.op using some interface from pyswagger.

**Comment by mission-liao** [comment]
No, I didn't provide such API.

I guess that you want to develop a data-driven test framework, if you have keep this in your test:
```
```

**Comment by mission-liao** [comment]
No, I didn't provide such API. And still, "username" is something you know before writing tests, why would you need to query it after loading definition?

I guess that you want to develop a data-driven test framework, if you have keep this in your test:
```
[
   "Tom"
]
```
Why can't you keep that:
```
{
   "username": "Tom"
}
```
Here is a suggestion when developing similar testing framework:
 - assign operationId to each Operation
 - organize all testing parameter in a json file to load
```json
{
   "getUserByName": {
      "username": "Tom"
   }
}
```

If I guess wrong, please correct me, :)

**Comment by LouisZou** [comment]
Thanks mission-liao.
I think that's a good idea.
I need to fix my test data to complete the test.
and this format can assure the integration of the test data.

**Comment by LouisZou** [comment]
Hi misson-liao, for this code "resp, req = myop(username="Tom")",
I have a question about it.
1. is myop a formal function point or reference?
    I want to get its list of arguments like "inspect.getargspec(myop)". because I want to know whether there is the argument "username" in this operation.
2. I want to call the api like "myop(user='a', body='b')", but sometimes the argument "body" or "user" is not exist. Now I can call it like the following:
 if mybody:
   myop(user='a', body=mybody)
else:
  myop(user='a')

is there more simple code to realize it?

**Comment by mission-liao** [comment]
1. myop should be a pyswagger.spec.v2_0.objects.Operation object, it implements __call__ method, so you can "call" it. And you can search this project for that object, there is no parameter like "username", everything is dynamic.

2. I can't understand your question. Here is an answer based on guess: only "required" parameter would be required & checked when initiating a request, others are ignored if not provided.

**Comment by LouisZou** [comment]
Thanks mission-liao.
"myop" is a variable in my source code ,that's meaning:
I will realize the following code:
if path and body:  -- that's meaning I need parameters named "username"  and body to set to this op
   req, resp = myop(username='Tom', body=mybody)
elif path:
  req, resp = myop(username='Tom')
elif body:
  req, resp = myop(body=mybody)
else : 
  req, resp = myop()

then -- resp.mime(..).
I think the code is complex. I want to set the mime into header first and then decide how to call the op with correct arguments.
just like:
myop.setMime(...)
client.request(myop(arguments))

is there any way?

**Comment by LouisZou** [comment]
if I call op directly without judging which parameters is needed just like the following:
req, resp = myop(username='Tom', body=mybody)
if there is no parameter in the op, it failed with "unknown parameter".

because in my code , I will iterate each of the APIs in swagger definition file and then do the same action.

**Comment by mission-liao** [comment]
But why would you pass unknown parameters when the swagger spec is a known one?

**Comment by LouisZou** [comment]
Hi mission-liao, I think I haven't explain my purpose clearly.
I want to iterate my definition file to get each API and then call it to verify it.
so in the code of loop ,just like:
for api in app.op.keys():
    myop=app.opp[api]

-- Now I don't know what parameters should be send to this variable "myop", sometimes body is needed, sometimes username is needed.

and then I have the test data from my data file just like:
 getUserByName  :  { "username": "Tom", "body":{}}

I also iterate the test data and get the real data to call "myop".
now I can call it like the following:
if not body:
  myop(username='Tom')

But I want to call it like this:
 myop(username='Tom', body={})

so I can use 1 line code without the sentence "if not body:".

**Comment by mission-liao** [comment]
If you already keep this
```
getUserByName : { "username": "Tom", "body":{}}
```
Then you can call it with
```python
d = data['getUserByName'] # get the dict
...
op(**d) # it just the same as op(username="Tom", body={}),
        # and you don't have to know 'username' and 'body' in advance.
```
refer to [this](http://stackoverflow.com/questions/36901/what-does-double-star-and-star-do-for-python-parameters) for details. If I still don't get your point, please forgive me :(.

**Comment by LouisZou** [comment]
Thanks mission for your advice.
I think I can fix my test data to assure the logic of my code.
just like this:
Operation1: {"username":"Tom"}
Operation2: {"body":{}}
Operation3: {"username":"Tom","body":{}}

because I know the required parameters for each operation in the test data, so I can specify them before do test.

**Comment by mission-liao** [comment]
Glad that you find some way to arrange testing datum.

**Comment by mission-liao** [comment]
It should be fine to close this issue, please feel free to reopen it when things go wrong.
