### ISSUE TITLE
pyswagger can handle the properties of object type is empty or not ?

### ISSUE THREAD

**Issue by WillaLuo** [mission-liao/pyswagger#73]
Hi mission, 
           I wonder whether pyswagger can handle this situation or not?
```json
"plan":{
   "type":"object",
   "additionalProperties":true,
   "properties":{

   }
},
"oplans":{
   "items":{
      "$ref":"#/definitions/plan"
   },
   "type":"array",
   "description":"List of oplans"
},

```

When I run client, the parameter of plan can't be validate successfully.
Thanks,
Shuang

**Comment by mission-liao** [comment]
Hi, I try this schema
```json
{
   "swagger":"2.0",
   "host":"http://test.com",
   "basePath":"/v1",
   "paths":{
      "/t":{
         "get":{
            "operationId":"kk",
            "parameters":[
               {
                  "in":"body",
                  "name":"body",
                  "schema":{
                     "$ref":"#/definitions/oplans"
                  }
               }
            ],
            "responses":{
               "default":{
                  "description":"void"
               }
            }
         }
      }
   },
   "definitions":{
      "plan":{
         "type":"object",
         "additionalProperties":true,
         "properties":{

         }
      },
      "oplans":{
         "items":{
            "$ref":"#/definitions/plan"
         },
         "type":"array",
         "description":"List of oplans"
      }
   }
}
```
with this code snippet:
```python
from pyswagger import SwaggerApp

app = SwaggerApp.create('swagger.json')

op = app.op["kk"]
req_and_resp = op(body=[
    dict(a=1, b=2, c=3),
    dict(name='john', email='xx@gmail.com'),
])
```
and it didn't raise any exception. If it's not what you expect, could you provide your code snippet / schema for me to investigate?

**Comment by WillaLuo** [comment]
Hi, mission,
     I try this schema , I modify the code snippet:
from pyswagger import SwaggerApp

app = SwaggerApp.create('swagger.json')

op = app.op["kk"]
req, resp = op(body=[
    dict(a=1, b=2, c=3),
    dict(name='john', email='xx@gmail.com'),
])

print req._p["body"]["body"]

please see the body value of req, the data (a=1, b=2, c=3) and (name='john', email='xx@gmail.com') is not validated and pass to body of req. 
`(virtualenv)-bash-4.1$ python test.py 
{},{}`

**Comment by mission-liao** [comment]
ya, u r right, that seems a bug.

**Comment by mission-liao** [comment]
I think I found the bug, for some reason, the cleanup of Model primitive is not called. 
You could patch pyswagger.primitive.__init__.py (L224) from
```python
if ret and cleanup and hasattr(ret, 'cleanup'):
```
to
```python
if ret != None and hasattr(ret, 'cleanup'):
```
before I provide an official fix.

**Comment by WillaLuo** [comment]
Ok, That's great, Thanks!
Shuang

2016-03-16 23:35 GMT+08:00 mission.liao <notifications@github.com>:

**Comment by WillaLuo** [comment]
Hi mission,
  I want to confirm with you about this: After you fix this bug and the
default additionproperties value, whether this schema object can be
validate successfully?
"oplans": {
                    "items": {
                        "type":"object",
                        "additionalproperties": true
                    },
                    "type": "array",
                    "description": "List of oplans"
                },

The "oplans" is an array of object, and the content of object can be
anything I want.
Thanks.
Shuang

2016-03-16 23:55 GMT+08:00 Willa luo <willa.l.luo@gmail.com>:

**Comment by mission-liao** [comment]
I think your schema object should be ok, I'll include it as a testing case to make sure it works in your workaround. But remember that, "additionalProperties: true" is not spec-compliant and might be fixed in the future.
