### ISSUE TITLE
python 3.5 fails 

### ISSUE THREAD

**Issue by zadoev** [mission-liao/pyswagger#74]
python3.5  

test_swagger.py is code got from quick start example with some codec modifications. Becase quick start example fails with unknown xml codec error

Error: 
Traceback (most recent call last):
  File "test_swagger.py", line 61, in <module>
    body=pet_Tom
  File "/home/cd/data/projects/python/pyswagger/pyswagger/contrib/client/requests.py", line 55, in request
    raw=six.StringIO(rs.content).getvalue()
TypeError: initial_value must be str or None, not bytes

It's because in python3 rs.content is binary string. So it fails here. 

Full output also attached. 
[log.txt](https://github.com/mission-liao/pyswagger/files/175346/log.txt)

[test_swagger.py.txt](https://github.com/mission-liao/pyswagger/files/175343/test_swagger.py.txt)

**Comment by mission-liao** [comment]
Thanks for your PR, it will be included in next version and released in this weekend.
