### ISSUE TITLE
Get a typeerror when using renderer

### ISSUE THREAD

**Issue by YoooFeng** [mission-liao/pyswagger#77]
Hi, recently i'm trying to use pyswagger(in python 2.7) to test my swagger spec. When i use renderer to test APIs, i got: TypeError: __call__() takes exactly 1 argument (2 given). 
  My code is the same as the tutorial/render.md:

app = SwaggerApp._create_('http://petstore.swagger.io/v2/swagger.json')
client = Client()
renderer = Renderer()
input_ = renderer.render_all(app.s('user').post)
resp = client.request(app.s('user').post(input_))

  I'm new in python, so who can tell me what's the problem?Thank you!

**Comment by mission-liao** [comment]
Sorry that the example for Render is invalid.....the correct one should be:
```python
resp = client.request(app.s('user').post(**input_))
```
because the accepted parameter of Operation.__call__ is **k. I'll fix this part in tutorial later. Thanks for reporting issues and welcome to python's world.

**Comment by YoooFeng** [comment]
Thank you so much for your response mission-liao, It works now!I am designing a tool that could autotest all APIs in swagger spec, it seems i have a long way to go :)

**Comment by mission-liao** [comment]
Ya, it would be a long way to go. Before cooking by yourself, did you try this one? https://github.com/Trax-air/swagger-tester. It looks a new library but would be worth to try.

**Comment by YoooFeng** [comment]
Thank you for your advise, I will have a try!
