### ISSUE TITLE
Swagger is renamed to OpenAPI

### ISSUE THREAD

**Issue by mission-liao** [mission-liao/pyswagger#80]
I'm considering to provide a renamed repo/package: pyopenapi, and everything in pyswagger should be renamed, too
 - pyswagger -> pyopenapi

The version of new package would stay up with this project.

In this project, all SwaggerXXX would be renamed to XXX, (original SwaggerXXX would still be kept as fallback), they are:
 - pyswagger.SwaggerApp -> App
 - pyswagger.resolve.SwaggerResolver -> Resolver
 - pyswagger.primitives.SwaggerPrimitive -> Primitive
 - pyswagger.SwaggerSecurity -> Security

I'm not going to move the whole code base to the new repo, instead, the new repo is only an wrapper on pyswagger (better to keep all commit history in one place)

**Comment by toabi** [comment]
Seems reasonable. Also leads to less duplicate naming.
