### ISSUE TITLE
1.2 to 2.0 converter

### ISSUE THREAD

**Issue by neokeats** [mission-liao/pyswagger#94]
Hi, 
is there a way to disable it ? 
or can you point to a version that works with directly 1.2 without converting it ? 
I have a lot of errors, even with Strict set to False.
I corrected them but it seems no end to it . 

Thanx.

```python
from pyswagger import SwaggerApp
app = SwaggerApp._create_('https://pp-my.kiwatch.com:443/restapi/api-docs', False)

File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyswagger/spec/base.py", line 276, in resolve
    obj = obj[t]
KeyError: 'admin/users!##!OrderDto'
```

**Comment by mission-liao** [comment]
The way that this project support multiple versions of OpenAPI is implementing everything with the latest version of OpenAPI, and convert older version to the latest version.

You can try this [version](https://github.com/mission-liao/pyswagger/releases/tag/0.0.2) but I guess your problem is related to some fundamental problem related to 1.2. If it's ok to you, you can upload your spec for me to check.

**Comment by neokeats** [comment]
thanx for the suggestion but even with 0.0.2, i get the same kind of errors. 

```python
from pyswagger import SwaggerApp
app = SwaggerApp._create_('https://pp-my.kiwatch.com:443/restapi/api-docs', False)

File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyswagger/utils.py", line 34, in __getitem__
    return super(ScopeDict, self).__getitem__(k)
KeyError: 'services/contact_details!##!MediaType'

```

the specs ? 
https://pp-my.kiwatch.com/restapidoc.htm
https://pp-my.kiwatch.com/restapi/api-docs
it's not my implementation, i just need to connect to their api, log-in and get some data.

**Comment by mission-liao** [comment]
I need the "resource_list.json" (the root document of Swagger 1.2) and other resource json files.

I've tried
 - https://pp-my.kiwatch.com/restapi/api-docs
    - {"errorMessage":"Could not find MessageBodyWriter for response object of type: com.wordnik.swagger.model.ResourceListing of media type: text/html","errorCode":3}
 - https://pp-my.kiwatch.com/restapi/api-docs/resource_list.json (404)
 - https://pp-my.kiwatch.com/restapi/api-docs/swagger.json (404)
 - https://pp-my.kiwatch.com/restapi/api-docs  <- it seems their Swagger UI, but need apiKey to access.

**Comment by neokeats** [comment]
they seems to have messed with their test version. 
the production version works : 
https://my.kiwatch.com/restapi/api-docs/

the ending / seems needed

**Comment by neokeats** [comment]
they were in maintenance, everything works fine now. 
thanx
