### ISSUE TITLE
pyswagger with javax.json.JsonObject valuetypes NUMBER & STRING

### ISSUE THREAD

**Issue by AlexeKorneev** [mission-liao/pyswagger#95]
Hi,

Could you help with one issue (if it's an issue): I'm using pyswagger library for rest api testing based on swagger.json file, everything worked absolutely fine until the moment when we tried the reference for
JsonObject (javax.json) in swagger.json file:

..."$ref" : "#/definitions/JsonValue"
```json
"definitions" : {
    "JsonValue" : {
      "type" : "object",
      "properties" : {
        "valueType" : {
          "type" : "string",
          "enum" : [ "ARRAY", "OBJECT", "STRING", "NUMBER", "TRUE", "FALSE", "NULL" ]
        }
      }
```

now by pushing usual json data: {'key': 'value'}, library returns always:
...  File "C:\Python27\lib\site-packages\six.py", line 599, in iteritems
    return d.items(**kw)
AttributeError: 'str' object has no attribute 'items'

By pushing same json-data with Postman (and other tools) and swagger UI it works perfectly fine, and valueType is interpreted as STRING in our rest API endpoint.

Any chance you could help, what could be the issue? Any tricks?
Thanks in advance.
Alexey

**Comment by mission-liao** [comment]
I'm not very clear about this issue you described, did you mean:
 - you have an API, which accept JsonValue as a parameter
 - you provide a string, and wish this library to convert it to JsonValue.

Could you provide a code example about "how to call that API"?

**Comment by AlexeKorneev** [comment]
Thanks for quick reply, here are more details, hopefully it will make it more clear:

We have a Java EE 7 JAX-RS rest endpoint that accepts javax.json.JsonObject as a PUT method parameter. One javax.json.JsonObject contains N amount of javax.json.JsonValue objects which all have a key as a String.

JsonObject structure:
{
key1:{jsonvalue1},
key2:{jsonvalue2},
}

For example, CURL command that works:
curl -H "Content-Type: application/json" -X PUT -i -k -d '{"keyToSomeValue": 5}' http://<host>:<port>/<path>

So the data is really simple json object containing key value pair. For example in this case the ValueType of this JsonValue would be ValueType.NUMBER and value of that JsonValue would be 5. And the key is keyToSomeValue.
JsonObject structure:
{
keyToSomeValue: {5} ,
}

curl -H "Content-Type: application/json" -X PUT -i -k -d '{"keyToSomeValue2": “other value”}' http://<host>:<port>/<path>

JsonObject structure:
{
keyToSomeValue2: {“other value”} ,
}

Now our problem is that we are not able to send this kind of json data using pyswagger library. JsonValue ValueType is always interpreted as ValueType.OBJECT because we are not able to send simple {‘key’:value} data. We are only able to send for example key={json object}.

Thanks!

**Comment by AlexeKorneev** [comment]
We have found an issue on our side. The issue was in usage of:
 "schema" : {
            "type" : "object",
            "additionalProperties" : {
              "$ref" : "#/definitions/JsonValue"
            }
"If additionalProperties is an object, that object is a schema that will be used to validate any additional properties not listed in properties." This was the problem in our case.

Thanks a lot for your support and providing this library. And sorry for false alarm.
We can close this item.

**Comment by mission-liao** [comment]
Good to know that your problem is resolved, and it's ok for false alarm.
